language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: ZAM48tWfe2biVONE7gQYhc910kK9yoF8vSyoXPYhvboqNT7gsw+oL9ODr773GLdVUMEbT1D+anMd4a01wHLdmRIkEx79h2cXv1o2OJwbnQBfMG9lOMOw3dFUG+DwHe/qMRXyGJDbOVEHsnhaFJ4JkDkrDGa/R2j99yWxfuF0zN7hWivdW2UaFc3545+ihSC6tY5fTesKUiNIm2JjhPD0SNwR9x+ejoAlWrS7Vj+0sT3Yh6CtZsaUJ0AszWdJZoOE+SljiVj6/hZqO0vuWKNOrbKE8x4t+7GgSDuF5ultUVPc5ymU3S3v7djaVnjYrNaSIVYQ1Ph2Rk03dEqT02SVzEj8gLWM9U4rtR8+toScCL0a5Lhr3wfw40upu8tWsUSk1TpuV8jHmYjoXBPbACc74VFoRuQgUr2IrrcDkBTculsNODzJ1hvDMqyzLp2PRfkZbRFn2BEYgbL4wCqEMntOHmn+ByXoCS0yiRVPO0125Vi7HjGX3OD12EsJb9CNplSFTsH1vXzV1ax6fkXcCtIgfMnaDlWM7p4SB5qPfeE5avGFRNkKb8NbcYFbc2AhgkdSPItlTplw2CS0tS0L2+/cbZf7Leb8jpZFTT+EPXSYwGf1AFob7tVlmMJRjNMfojq+nSuNkWxWIcXBE5ax/DlWhgn0pKOLw0+SqfL8rapIAxI=
  file:
    - "remark-breaks.js"
    - "remark-breaks.min.js"
  on:
    tags: true
